export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ys-custom"
plugins=(git)
source $ZSH/oh-my-zsh.sh

export PNPM_HOME=/home/node/.local/share/pnpm
export NPM_CONFIG_PREFIX=/home/node/.npm-global
export PATH=/home/node/.npm-global/bin:$PNPM_HOME:$PATH

# no TTY for pnpm's purge / supply-chain prompts
export CI=true

# CI=true makes node report color depth 1; restore truecolor
export FORCE_COLOR=3
